export default {
    articleList: [
        { title: '前端Web安全', link: 'https://ymlog.cn/', time: '2018/4/1' },
        { title: '前端Web安全', link: 'https://ymlog.cn/', time: '2018/4/2' },
        { title: '前端Web安全', link: 'https://ymlog.cn/', time: '2018/4/3' },
        { title: '前端Web安全', link: 'https://ymlog.cn/', time: '2018/4/4' },
        { title: '前端Web安全', link: 'https://ymlog.cn/', time: '2018/4/5' },
        { title: '前端Web安全', link: 'https://ymlog.cn/', time: '2018/4/6' },
        { title: '前端Web安全', link: 'https://ymlog.cn/', time: '2018/4/7' },
        { title: '前端Web安全', link: 'https://ymlog.cn/', time: '2018/4/8' },
        { title: '前端Web安全', link: 'https://ymlog.cn/', time: '2018/4/10' },
        { title: '前端Web安全', link: 'https://ymlog.cn/', time: '2018/4/11' },
        { title: '前端Web安全', link: 'https://ymlog.cn/', time: '2018/4/12' },
        { title: '前端Web安全', link: 'https://ymlog.cn/', time: '2018/4/13' },
        { title: '前端Web安全', link: 'https://ymlog.cn/', time: '2018/4/14' },
        { title: '前端Web安全', link: 'https://ymlog.cn/', time: '2018/4/15' },
        { title: '前端Web安全', link: 'https://ymlog.cn/', time: '2018/4/16' },
        { title: '前端Web安全', link: 'https://ymlog.cn/', time: '2018/4/17' },
        { title: '前端Web安全', link: 'https://ymlog.cn/', time: '2018/4/18' },
    ],
    timeline: [
        { time: '04/2021', count: '10' },
        { time: '03/2021', count: '03' },
        { time: '02/2021', count: '05' },
        { time: '01/2020', count: '09' },
        { time: '12/2020', count: '11' },
        { time: '11/2020', count: '07' },
        { time: '10/2020', count: '05' },
    ]
}